version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on 'date'
      - mvn package
      - mv target/*.war ./p2_api.war
  post_build:
    commands:
      - echo Build completed on 'date'
      - unzip p2_api.war -d artifact/
      - mv artifact/WEB-INF WEB-INF
artifacts:
  files:
    - WEB-INF/**/*
  name: artifact